### ISSUE TITLE
Assemble the car parts

### ISSUE THREAD

**Issue by Basel1Hassan** [BaherAbdelfatah/ASUMobiCarG60#2]
I'll give you the car to assemble it and test the motors

**Comment by ehababdelghany** [comment]
[
![img-20180301-wa0002](https://user-images.githubusercontent.com/36567468/37003135-b236c5e0-20d4-11e8-9e2f-b0a9220219ff.jpg)
![img-20180301-wa0000](https://user-images.githubusercontent.com/36567468/37003148-bae3a348-20d4-11e8-8c5e-128d168ad149.jpg)

](url)
